# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-17.8

# User packages to be built.
packages:
- '.'

# Extra package dependencies
extra-deps:
- relapse-1.0.0.0@sha256:b89ea23189e07f377be4e2a4deccf3d6ba7f547ed8ad77e27b35d78801efd81c

# Dependencies bounds
pvp-bounds: both

# Nix integration
nix:
    packages:
    - zlib
    - boost
    - jsoncpp
    - solc
    - haskellPackages.hlint
    - haskellPackages.stylish-haskell
